### ISSUE TITLE
Ticket #3 - Créer un batch de rappel des prêts arrivant bientôt à expiration

### ISSUE THREAD

**Issue by navispeed** [Kybox/KyLibrary2#3]
Nous aimerions, en parallèle de la correction de la gestion des prolongations de prêt (cf ticket #2), ajouter un mécanisme de rappel aux usagers des prêts arrivant bientôt à expiration. Les usagers qui le souhaitent pourront activer une option (dans leur profil sur l’application web) qui leur enverra un mail de rappel 5 jours calendaires avant la fin de leur prêt. Le mail contiendra la liste de leurs prêts en cours qui arrivent à expiration dans 5 jours ou moins avec la date d’expiration associée à chaque prêt.
Cette option sera à activer par défaut pour tous les utilisateurs lors de la mise en production.
Cette demande n’est pas urgente, vous livrerez cette évolution en même temps que celle demandé dans le ticket #1.

**Comment by Kybox** [comment]
L'option d'activation/désactivation des notifications concernant les prêts arrivant à expiration est disponible pour chaque utilisateur sur l'interface graphique client (après authentification).

Le batch est désormais opérationnel et s’exécute quotidiennement à 02:00 AM afin d'envoyer les notifications aux clients.

La développement de la fonctionnalité est terminée.
Les livrables seront disponibles dans la version 2.0-RELEASE avec les améliorations du ticket #1.
